branch-defaults:
  master:
    environment: master-TaxPlusAws01-env
global:
  application_name: tax-plus-aws-01
  default_ec2_keyname: tax-plus
  default_platform: 64bit Amazon Linux 2018.03 v4.8.2 running Node.js
  default_region: ap-northeast-1
  sc: git
